project:
  type: website

website:
  title: "rdiscovery"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Layalchristine24/rdiscovery
      - icon: twitter
        href: https://twitter.com/LettryL
      - icon: linkedin
        href: https://linkedin.com/in/layal-christine-lettry-529b4471/
      - icon: mastodon
        href: https://fosstodon.org/@layal
  site-url: "https://rdiscovery.netlify.app"
  
format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css

editor: visual
execute:
  freeze: auto
