project:
  type: website

website:
  title: "rdiscovery"
  description: "Explore R with Layal Christine Lettry"
  navbar:
    title: false
    background: "#0571B0"
    left:
      - href: index.qmd
        text: Home
      - href: index.xml
        text: RSS
    right:
      - about.qmd
      - text: Sites
        menu:
        - href: http://layalchristinelettry.rbind.io/
          text: Homepage
        - href: https://rdiscovery.netlify.app
          text: rdiscovery Blog
      - text: GitHub
        menu:
        - icon: github
          href: https://github.com/Layalchristine24/rdiscovery
          text: Blog Repository
        - icon: github
          href: https://github.com/Layalchristine24
          text: Layalchristine24 Profile
        - icon: github
          href: https://github.com/cynkra
          text: cynkra GmbH
        - icon: github
          href: https://github.com/asam-group
          text: ASAM Group
      - text: Social
        menu:
        - icon: twitter
          href: https://twitter.com/LettryL
          text: Twitter
        - icon: linkedin
          href: https://linkedin.com/in/layal-christine-lettry-529b4471/
          text: LinkedIn
        - icon: mastodon
          href: https://fosstodon.org/@layal
          text: Mastodon
      - text: Research
        menu: 
        - href: https://orcid.org/0009-0008-6396-0523
          text: ORCID
        - href: https://www.researchgate.net/profile/Layal-Lettry
          text: ResearchGate
        - href: https://unifr.academia.edu/LayalChristineLettry
          text: Academia
        - href: https://scholar.google.com/citations?user=YxD9LGQAAAAJ&hl=fr
          text: Google Scholar
        - href: https://stackexchange.com/users/28214106/layal-christine-lettry
          text: StackExchange
        
  page-footer:
    center:
      - href: https://rdiscovery.netlify.app
        text: rdiscovery.netlify.app
  site-url: https://rdiscovery.netlify.app
  repo-url: https://github.com/Layalchristine24/rdiscovery
  open-graph: true
  search: false
  
format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    include-after-body: plausible.html

editor: visual
execute:
  freeze: auto
