project:
  type: website

website:
  title: "rdiscovery"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  site-url: "https://rdiscovery.netlify.app"
  
format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css

editor: visual
execute:
  freeze: auto
